#
#    ____   ____.___    _________       _____  __                                 
# \   \ /   /|   |  /   _____/ _____/ ____\/  |___  _  _______ _______   ____  
#  \   Y   / |   |  \_____  \ /  _ \   __\\   __\ \/ \/ /\__  \\_  __ \_/ __ \ 
#  \     /  |   |  /        (  <_> )  |   |  |  \     /  / __ \|  | \/\  ___/ 
#   \___/   |___| /_______  /\____/|__|   |__|   \/\_/  (____  /__|    \___  >
#                         \/                                 \/            \/ 
#                         
#                         
#    Copyright 2024 (©) VI Software y contribuidores. Todos los derechos reservados.
#    
#    GitHub: https://github.com/VI-Software
#    Documentación: https://docs-vis.galnod.com/vi-software/vis-launcher
#    Web: https://vis.galnod.com
#    Licencia del proyecto: https://github.com/VI-Software/vis-launcher/blob/main/LICENSE

[ejs.app]
title = "VI Software Launcher"

[ejs.landing]
mediaGitHubURL = "https://github.com/VI-Software"
mediaDiscordURL = "https://vis.galnod.com/discord"

[ejs.settings]
sourceGithubLink = "https://github.com/VI-Software/vis-launcher"
supportLink = "https://github.com/VI-Software/vis-launcher/issues"

[ejs.welcome]
welcomeHeader = "Bienvenido/a a VI Software Launcher"
welcomeDescription = 'Este launcher fue desarrollado por el equipo de VI Software para facilitar la gestión de modpacks en las experiencias VIS. Al utilizar este launcher, aceptas la <a style="color: purple;" href="https://docs-vis.galnod.com/vi-software/vis-launcher/politica-de-privacidad">política de privacidad</a> y <a href="https://docs-vis.galnod.com/vi-software/vis-launcher/terminos-de-uso" style="color: purple;">términos de servicio</a> de VI Software'
welcomeDescCTA = "¡La diversión está a la vuelta de la esquina!"
