#    ____   ____.___    _________       _____  __                                 
# \   \ /   /|   |  /   _____/ _____/ ____\/  |___  _  _______ _______   ____  
#  \   Y   / |   |  \_____  \ /  _ \   __\\   __\ \/ \/ /\__  \\_  __ \_/ __ \ 
#   \     /  |   |  /        (  <_> )  |   |  |  \     /  / __ \|  | \/\  ___/ 
#    \___/   |___| /_______  /\____/|__|   |__|   \/\_/  (____  /__|    \___  >
#                          \/                                 \/            \/ 
#                          
#     Â© 2025 VI Software. All rights reserved.
# 
#     License: AGPL-3.0
#    https://www.gnu.org/licenses/agpl-3.0.en.html
#
#    GitHub: https://github.com/VI-Software
#    Website: https://visoftware.dev

[ejs.app]
title = "VI Software Launcher"
title_nightly = "VI Software Launcher Nightly"
title_canary = "VI Software Launcher Canary"
[ejs.landing]
websiteURL = "https://visoftware.dev"
mediaGitHubURL = "https://github.com/VI-Software"
mediaDiscordURL = "https://visoftware.dev/discord"
canaryWebsiteURL = "https://visoftware.dev/launcher"

[ejs.settings]
sourceGithubLink = "https://github.com/VI-Software/vis-launcher"
supportLink = "https://github.com/VI-Software/vis-launcher/issues"

[launcher]
guestModeEnabled = true
